services:
  caddy:
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    network_mode: host
    volumes:
      - caddy-data:/data
      - caddy-config:/config

volumes:
  caddy-data:
    name: 'chatsift-caddy-data'
    external: true
  caddy-config:
    name: 'chatsift-caddy-config'
    external: true
